# This is a basic workflow to help you get started with Actions

name: qd

# Controls when the workflow will run
on:
  push:
    branches: [ main ]
  schedule:
    # 定时任务，在每天的5点执行任务
    - cron: '21 13 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  my-job:
    name: qd
    runs-on: ubuntu-latest
    steps:      
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: execute the task
        run: java -jar dailyCheckIn-1.0.0.jar
        
      - name: execute the task2
        run: java -jar dailyCheckIn-1.0.0-lz.jar